const std = @import("std");

const schema_mod = @import("schema.zig");
const Field = schema_mod.Field;
const FieldType = schema_mod.FieldType;
const HasManyRelationship = schema_mod.HasManyRelationship;
const Relationship = schema_mod.Relationship;
const model = @import("model_gen/model.zig");
const query = @import("model_gen/query.zig");
const utils = @import("model_gen/utils.zig");
const TableSchema = @import("table.zig").TableSchema;

pub fn generateModel(allocator: std.mem.Allocator, schema: TableSchema, schema_file: []const u8, output_dir: []const u8, table_map: std.StringHashMap([]const u8)) !void {
    const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
    defer allocator.free(struct_name);

    // Create sub-directory using table name directly: src/models/generated/{table_name}/
    const model_dir = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ output_dir, schema.name });
    defer allocator.free(model_dir);

    std.fs.cwd().makePath(model_dir) catch |err| {
        if (err != error.PathAlreadyExists) {
            std.debug.print("Error creating directory '{s}': {}\n", .{ model_dir, err });
            return err;
        }
    };

    // Generate model declarations and logic (model.zig)
    try generateModelFile(allocator, schema, struct_name, schema_file, model_dir, table_map);

    // Generate query builder extensions (query.zig)
    try generateQueryFile(allocator, schema, schema_file, model_dir);
}

pub fn generateRegistryFile(allocator: std.mem.Allocator, schemas: []const TableSchema, output_dir: []const u8) !void {
    const file_name = try std.fmt.allocPrint(allocator, "{s}/registry.zig", .{output_dir});
    defer allocator.free(file_name);

    var output = std.ArrayList(u8){};
    defer output.deinit(allocator);
    const writer = output.writer(allocator);

    try writer.writeAll("// AUTO-GENERATED CODE - DO NOT EDIT\n");
    try writer.writeAll("// Generated by scripts/generate_model.zig\n\n");

    try writer.writeAll(
        \\const std = @import("std");
        \\const pg = @import("pg");
        \\
    );

    // Import all models
    for (schemas) |schema| {
        const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
        defer allocator.free(struct_name);

        try writer.print("pub const {s} = @import(\"{s}/model.zig\");\n", .{ struct_name, schema.name });
    }

    try writer.writeAll("\n");

    // Generate Client struct
    try writer.writeAll(
        \\pub const Client = struct {
        \\    // Stateless client: simply acts as a namespace for models.
        \\    // This allows access like: Client.Users.findById(db, ...)
        \\    // which supports both pool and transaction based execution.
        \\
    );
    for (schemas) |schema| {
        const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
        defer allocator.free(struct_name);

        try writer.print("    pub const {s} = @import(\"{s}/model.zig\");\n", .{ struct_name, schema.name });
    }

    // Add Rel namespace for relation types
    try writer.writeAll("\n    // Relation types for eager loading (use with fetchAs)\n");
    try writer.writeAll("    pub const Rel = struct {\n");
    for (schemas) |schema| {
        // Only include tables that have relationships
        const has_relationships = schema.relationships.items.len > 0 or schema.has_many_relationships.items.len > 0;
        if (!has_relationships) continue;

        const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
        defer allocator.free(struct_name);
        try writer.print("        pub const {s} = @import(\"{s}/rel.zig\");\n", .{ struct_name, schema.name });
    }
    try writer.writeAll("    };\n");

    try writer.writeAll("};\n\n");

    // Generate Tables enum
    try writer.writeAll("pub const Tables = enum {\n");
    for (schemas) |schema| {
        try writer.print("    {s},\n", .{schema.name});
    }
    try writer.writeAll("\n    pub fn isFieldDateTime(self: @This(), field_name: []const u8) bool {\n");
    try writer.writeAll("        return switch (self) {\n");
    for (schemas) |schema| {
        const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
        defer allocator.free(struct_name);
        try writer.print(
            \\            .{s} => if (std.meta.stringToEnum({s}.FieldEnum, field_name)) |f| f.isDateTime() else false,
            \\
        , .{ schema.name, struct_name });
    }
    try writer.writeAll("        };\n");
    try writer.writeAll("    }\n");

    try writer.writeAll("\n    pub fn jsonAllFieldsSql(self: @This()) []const u8 {\n");
    try writer.writeAll("        return switch (self) {\n");
    for (schemas) |schema| {
        const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
        defer allocator.free(struct_name);
        try writer.print("            .{s} => {s}.json_all_fields_sql,\n", .{ schema.name, struct_name });
    }
    try writer.writeAll("        };\n");
    try writer.writeAll("    }\n");
    try writer.writeAll("};\n\n");

    // Generate TableFields struct
    try writer.writeAll("pub const TableFields = struct {\n");
    for (schemas) |schema| {
        const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
        defer allocator.free(struct_name);
        try writer.print("    {s}: {s}.FieldEnum,\n", .{ schema.name, struct_name });
    }
    try writer.writeAll("};\n\n");

    // Generate TableFieldsUnion
    try writer.writeAll("pub const TableFieldsUnion = union(Tables) {\n");
    for (schemas) |schema| {
        const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
        defer allocator.free(struct_name);
        try writer.print("    {s}: {s}.FieldEnum,\n", .{ schema.name, struct_name });
    }
    try writer.writeAll(
        \\
        \\    pub fn toString(self: @This()) []const u8 {
        \\        return switch (self) {
    );
    for (schemas) |schema| {
        try writer.print("            .{s} => |f| @tagName(f),\n", .{schema.name});
    }
    try writer.writeAll(
        \\        };
        \\    }
        \\};
    );

    try std.fs.cwd().writeFile(.{ .sub_path = file_name, .data = output.items });

    // Let's create `root.zig` that re-exports everything from registry.zig
    const root_file_name = try std.fmt.allocPrint(allocator, "{s}/root.zig", .{output_dir});
    defer allocator.free(root_file_name);

    var root_output = std.ArrayList(u8){};
    defer root_output.deinit(allocator);
    const root_writer = root_output.writer(allocator);

    try root_writer.writeAll("// AUTO-GENERATED CODE - DO NOT EDIT\n");
    try root_writer.writeAll("pub const Client = @import(\"registry.zig\").Client;\n\n");

    for (schemas) |schema| {
        const struct_name = try utils.toPascalCaseNonSingular(allocator, schema.name);
        defer allocator.free(struct_name);
        try root_writer.print("pub const {s} = Client.{s};\n", .{ struct_name, struct_name });
    }
    try root_writer.writeAll("pub const Rel = Client.Rel;\n\n");
    try root_writer.writeAll("pub const Executor = @import(\"executor.zig\").Executor;\n\n");
    try root_writer.writeAll("pub const Transaction = @import(\"transaction.zig\").Transaction;\n\n");

    try std.fs.cwd().writeFile(.{ .sub_path = root_file_name, .data = root_output.items });

    std.debug.print("✅ Generated: {s} & root.zig\n", .{file_name});
}

// Helper to generate the main model file
fn generateModelFile(allocator: std.mem.Allocator, schema: TableSchema, struct_name: []const u8, schema_file: []const u8, output_dir: []const u8, table_map: std.StringHashMap([]const u8)) !void {
    const file_name = try std.fmt.allocPrint(allocator, "{s}/model.zig", .{output_dir});
    defer allocator.free(file_name);

    var output = std.ArrayList(u8){};
    defer output.deinit(allocator);
    const writer = output.writer(allocator);

    // Calculate final fields
    const final_fields = try utils.getFinalFields(allocator, schema);
    defer allocator.free(final_fields);

    // Generate header
    try model.generateHeader(writer, schema_file);

    // Generate imports
    try model.generateModelImports(writer, schema, allocator, table_map);

    // Generate struct definition (Strict)
    try model.generateStructDefinition(writer, schema, struct_name, final_fields, allocator);

    // Generate Deinit
    try model.generateDeinit(writer, final_fields, allocator);

    // Generate CreateInput
    try model.generateCreateInput(writer, final_fields, allocator);

    // Generate UpdateInput
    try model.generateUpdateInput(writer, final_fields, allocator);

    // Generate SQL methods
    const has_upsert = try model.generateSQLMethods(writer, schema, struct_name, final_fields, allocator);

    // Generate base
    try model.generateBaseModelWrapper(writer, struct_name);

    // Generate DDL wrappers
    try model.generateDDLWrappers(writer);

    // Generate CRUD wrappers
    try model.generateCRUDWrappers(writer, struct_name, has_upsert);

    // Generate JSON response helpers
    try model.generateJsonResponseHelpers(writer, struct_name, final_fields);

    // Generate relationship methods
    try model.generateRelationshipMethods(writer, schema, struct_name, allocator);

    // Write to file
    try std.fs.cwd().writeFile(.{ .sub_path = file_name, .data = output.items });

    std.debug.print("    -> Created {s}/model.zig\n", .{output_dir});

    // Generate rel.zig with explicit relation types
    try generateRelFile(allocator, schema, struct_name, final_fields, output_dir);
}

fn generateQueryFile(allocator: std.mem.Allocator, schema: TableSchema, schema_file: []const u8, output_dir: []const u8) !void {
    const file_name = try std.fmt.allocPrint(allocator, "{s}/query.zig", .{output_dir});
    defer allocator.free(file_name);

    var output = std.ArrayList(u8){};
    defer output.deinit(allocator);
    const writer = output.writer(allocator);

    try query.generateHeader(writer, schema_file);

    // Imports
    try query.generateImports(writer, schema);

    try query.generateStructDefinition(writer);

    try query.generatePubMethods(writer, schema, allocator);
    try std.fs.cwd().writeFile(.{ .sub_path = file_name, .data = output.items });
    std.debug.print("    -> Created {s}/query.zig\n", .{output_dir});
}

fn generateRelFile(allocator: std.mem.Allocator, schema: TableSchema, struct_name: []const u8, fields: []const Field, output_dir: []const u8) !void {
    const file_name = try std.fmt.allocPrint(allocator, "{s}/rel.zig", .{output_dir});
    defer allocator.free(file_name);

    var output = std.ArrayList(u8){};
    defer output.deinit(allocator);
    const writer = output.writer(allocator);

    try model.generateRelationTypes(writer, schema, struct_name, fields, allocator);

    // Only write file if there's content (has relations)
    if (output.items.len > 0) {
        try std.fs.cwd().writeFile(.{ .sub_path = file_name, .data = output.items });
        std.debug.print("    -> Created {s}/rel.zig\n", .{output_dir});
    }
}

// MARK: - CLI Entry Point

const generateRegistry = @import("registry_generator.zig").generateRegistry;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 3) {
        std.debug.print("Usage: {s} <schemas_directory> [output_directory] [sql_output_directory] [--skip-migrations]\n", .{args[0]});
        std.debug.print("Example: {s} schemas src/models/generated migrations\n", .{args[0]});
        std.debug.print("Example with skip: {s} schemas src/models/generated --skip-migrations\n", .{args[0]});
        std.debug.print("\nThis generates registry.zig and runner.zig in the schemas directory.\n", .{});
        std.debug.print("Then add a build step in your build.zig to run the runner.\n", .{});
        return error.MissingArgument;
    }

    var skip_migrations = false;
    var arg_index = args.len - 1;
    if (arg_index >= 2 and std.mem.eql(u8, args[arg_index], "--skip-migrations")) {
        skip_migrations = true;
        arg_index -= 1;
    }

    const schemas_dir = args[1];
    const output_dir = if (arg_index >= 2) args[2] else "src/models/generated";
    const sql_output_dir = if (arg_index >= 3) args[3] else "migrations";

    std.debug.print("Scanning schemas directory: {s}\n", .{schemas_dir});
    std.debug.print("Output directory for models: {s}\n\n", .{output_dir});

    // 1. Generate Registry
    const registry_path = try std.fmt.allocPrint(allocator, "{s}/registry.zig", .{schemas_dir});
    defer allocator.free(registry_path);

    try generateRegistry(schemas_dir, registry_path);
    std.debug.print("✅ Generated registry at {s}\n", .{registry_path});

    // 2. Generate Runner Script
    const runner_path = try std.fmt.allocPrint(allocator, "{s}/runner.zig", .{schemas_dir});
    defer allocator.free(runner_path);

    try generateRunner(
        allocator,
        runner_path,
        output_dir,
        sql_output_dir,
        schemas_dir,
        skip_migrations,
    );
    std.debug.print("✅ Generated runner at {s}\n", .{runner_path});

    // Copy base model files to output directory
    try copyBaseModel(allocator, output_dir);

    // 3. Print next steps for the user
    std.debug.print("\n🎉 Generation complete!\n", .{});
    std.debug.print("\n📋 Next steps:\n", .{});
    std.debug.print("   Add this to your build.zig to run the model generator:\n\n", .{});
    std.debug.print("   // Model runner step\n", .{});
    std.debug.print("   const runner_exe = b.addExecutable(.{{\n", .{});
    std.debug.print("       .name = \"model-runner\",\n", .{});
    std.debug.print("       .root_module = b.createModule(.{{\n", .{});
    std.debug.print("           .root_source_file = b.path(\"{s}\"),\n", .{runner_path});
    std.debug.print("           .target = target,\n", .{});
    std.debug.print("           .optimize = optimize,\n", .{});
    std.debug.print("           .imports = &.{{\n", .{});
    std.debug.print("               .{{ .name = \"fluentorm\", .module = fluentorm }},\n", .{});
    std.debug.print("           }},\n", .{});
    std.debug.print("       }}),\n", .{});
    std.debug.print("   }});\n", .{});
    std.debug.print("   const run_runner = b.step(\"generate-models\", \"Generate models from schemas\");\n", .{});
    std.debug.print("   run_runner.dependOn(&b.addRunArtifact(runner_exe).step);\n\n", .{});
    std.debug.print("   Then run: zig build generate-models\n", .{});
}

fn generateRunner(
    allocator: std.mem.Allocator,
    output_path: []const u8,
    output_dir: []const u8,
    sql_output_dir: []const u8,
    schemas_dir: []const u8,
    skip_migrations: bool,
) !void {
    const file = try std.fs.cwd().createFile(output_path, .{});
    defer file.close();

    const migration_code = if (skip_migrations) "" else 
        \\
        \\    // Create snapshot of current schema state
        \\    const current_snapshot = try snapshot.createDatabaseSnapshot(allocator, schemas);
        \\    defer current_snapshot.deinit(allocator);
        \\
        \\    // Try to load previous snapshot
        \\    const prev_snapshot_result = try snapshot.loadSnapshot(allocator, snapshot_file);
        \\
        \\    // Compute diff and generate migrations
        \\    if (prev_snapshot_result) |prev| {
        \\        defer prev.deinit();
        \\
        \\        const schema_diff = try diff.diffSnapshots(allocator, prev.value, current_snapshot);
        \\        defer schema_diff.deinit(allocator);
        \\
        \\        if (schema_diff.has_changes) {
        \\            // Generate incremental migration files - one per change
        \\            const generated_files = try sql_generator.writeIncrementalMigrationFiles(allocator, schema_diff, sql_output_dir);
        \\            defer {
        \\                for (generated_files) |f| allocator.free(f);
        \\                allocator.free(generated_files);
        \\            }
        \\
        \\            std.debug.print("Generated{d} migration file(s):\n", .{generated_files.len});
        \\            for (generated_files) |f| {
        \\                std.debug.print("  - {s}\n", .{f});
        \\            }
        \\        } else {
        \\            std.debug.print("No schema changes detected.\n", .{});
        \\        }
        \\    } else {
        \\        // First run - generate initial migration with all tables
        \\        const schema_diff = try diff.diffSnapshots(allocator, null, current_snapshot);
        \\        defer schema_diff.deinit(allocator);
        \\
        \\        if (schema_diff.has_changes) {
        \\            // Generate incremental migration files - one per change
        \\            const generated_files = try sql_generator.writeIncrementalMigrationFiles(allocator, schema_diff, sql_output_dir);
        \\            defer {
        \\                for (generated_files) |f| allocator.free(f);
        \\                allocator.free(generated_files);
        \\            }
        \\
        \\            std.debug.print("Generated {d} initial migration file(s):\n", .{generated_files.len});
        \\            for (generated_files) |f| {
        \\                std.debug.print("  - {s}\n", .{f});
        \\            }
        \\        }
        \\    }
        \\
        \\    // Save current snapshot for next run
        \\    try snapshot.saveSnapshot(allocator, current_snapshot, snapshot_file);
        \\    std.debug.print("Snapshot saved to {s}\n", .{snapshot_file});
        \\
    ;

    const imports = if (skip_migrations)
        \\const std = @import("std");
        \\const registry = @import("registry.zig");
        \\const fluentorm = @import("fluentorm");
        \\const model_generator = fluentorm.model_generator;
        \\
    else
        \\const std = @import("std");
        \\const registry = @import("registry.zig");
        \\const fluentorm = @import("fluentorm");
        \\const sql_generator = fluentorm.sql_generator;
        \\const model_generator = fluentorm.model_generator;
        \\const snapshot = fluentorm.snapshot;
        \\const diff = fluentorm.diff;
        \\
    ;

    const make_path_sql = if (skip_migrations) "" else 
        \\    try std.fs.cwd().makePath(sql_output_dir);
        \\
    ;

    var sql_path: []const u8 = undefined;
    if (skip_migrations) {
        sql_path = "";
    } else {
        sql_path = try std.fmt.allocPrint(allocator,
            \\    const sql_output_dir = "{s}";
            \\    const snapshot_file = "{s}/.fluent_snapshot.json";
        , .{
            sql_output_dir,
            schemas_dir,
        });
    }

    const content = try std.fmt.allocPrint(allocator,
        \\{s}
        \\pub fn main() !void {{
        \\    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
        \\    defer arena.deinit();
        \\    const allocator = arena.allocator();
        \\
        \\    // Use merged schemas - multiple schema files with same table_name are combined
        \\    const schemas = try registry.getAllSchemas(allocator);
        \\    defer {{
        \\        for (schemas) |*s| s.deinit();
        \\        allocator.free(schemas);
        \\    }}
        \\
        \\    const output_dir = "{s}";
        \\    {s}
        \\
        \\    try std.fs.cwd().makePath(output_dir);
        \\{s}
        \\{s}
        \\    // Build table name -> directory name mapping
        \\    // This handles cases where schema.name might differ from the actual directory name
        \\    var table_map = std.StringHashMap([]const u8).init(allocator);
        \\    defer {{
        \\        var it = table_map.valueIterator();
        \\        while (it.next()) |v| allocator.free(v.*);
        \\        table_map.deinit();
        \\    }}
        \\    for (schemas) |schema_item| {{
        \\        // Use table name directly as directory name
        \\        const dir_name = try allocator.dupe(u8, schema_item.name);
        \\        try table_map.put(schema_item.name, dir_name);
        \\    }}
        \\
        \\    // Generate models (always)
        \\    for (schemas) |schema_item| {{
        \\        const schema_file = try std.fmt.allocPrint(allocator, "{{s}}.zig", .{{schema_item.name}});
        \\        defer allocator.free(schema_file);
        \\        try model_generator.generateModel(allocator, schema_item, schema_file, output_dir, table_map);
        \\    }}
        \\
        \\    try model_generator.generateRegistryFile(allocator, schemas, output_dir);
        \\    std.debug.print("Models generated in {{s}}\n", .{{output_dir}});
        \\}}
        \\
    , .{ imports, output_dir, sql_path, make_path_sql, migration_code });
    if (!skip_migrations) allocator.free(sql_path);
    defer allocator.free(content);

    try file.writeAll(content);
}

/// Copy base.zig, query.zig, and transaction.zig to the output directory
fn copyBaseModel(allocator: std.mem.Allocator, output_dir: []const u8) !void {
    const base_dest_path = try std.fmt.allocPrint(allocator, "{s}/base.zig", .{output_dir});
    const query_builder_dest_path = try std.fmt.allocPrint(allocator, "{s}/query.zig", .{output_dir});
    const transaction_dest_path = try std.fmt.allocPrint(allocator, "{s}/transaction.zig", .{output_dir});
    const executor_dest_path = try std.fmt.allocPrint(allocator, "{s}/executor.zig", .{output_dir});
    const error_dest_path = try std.fmt.allocPrint(allocator, "{s}/error.zig", .{output_dir});
    defer allocator.free(base_dest_path);
    defer allocator.free(query_builder_dest_path);
    defer allocator.free(transaction_dest_path);
    defer allocator.free(executor_dest_path);
    defer allocator.free(error_dest_path);

    // Embed source files directly into the executable
    const base_content = @embedFile("base.zig");
    const query_content = @embedFile("query.zig");
    const transaction_content = @embedFile("transaction.zig");
    const executor_content = @embedFile("executor.zig");
    const error_content = @embedFile("error.zig");

    // Ensure output directory exists
    std.fs.cwd().makePath(output_dir) catch |err| {
        if (err != error.PathAlreadyExists) return err;
    };

    // Write to output directory (always overwrite to ensure latest version)
    try std.fs.cwd().writeFile(.{
        .sub_path = base_dest_path,
        .data = base_content,
    });

    try std.fs.cwd().writeFile(.{
        .sub_path = query_builder_dest_path,
        .data = query_content,
    });

    try std.fs.cwd().writeFile(.{
        .sub_path = transaction_dest_path,
        .data = transaction_content,
    });

    try std.fs.cwd().writeFile(.{
        .sub_path = executor_dest_path,
        .data = executor_content,
    });

    try std.fs.cwd().writeFile(.{
        .sub_path = error_dest_path,
        .data = error_content,
    });

    std.debug.print("📦 Bundled base.zig to {s}\n", .{base_dest_path});
    std.debug.print("📦 Bundled query.zig to {s}\n", .{query_builder_dest_path});
    std.debug.print("📦 Bundled transaction.zig to {s}\n", .{transaction_dest_path});
    std.debug.print("📦 Bundled executor.zig to {s}\n", .{executor_dest_path});
    std.debug.print("📦 Bundled error.zig to {s}\n", .{error_dest_path});
}
